Fix missing <unistd.h> header for sleep(3) definition (#52)
Clean up build warning:
src/calibrate.c: In function ‘Calibrate’:
src/calibrate.c:32:9: warning: implicit declaration of function ‘sleep’ [-Wimplicit-function-declaration]
   32 |         sleep(1);

Signed-off-by: Colin Ian King <colin.i.king@gmail.com>